"""
Plugin vendor and product alias data for matching.
Researched from official vendor sites, DAW plugin lists, and common FL Studio display names.
Vendors: 100+; products: most-used third-party + FL natives.
"""

# Vendor name (canonical) -> set of aliases as shown in FL/DAW or scan
# Used to strip vendor from ref names so "Native Instruments Kontakt 7" matches "Kontakt 7"
VENDOR_ALIASES = {
    "native instruments": {"ni", "nativeinstruments", "native instruments", "native instrument"},
    "izotope": {"i zotope", "izotope inc", "izotopeinc", "izotope", "i zotope inc"},
    "xfer": {"xfer records", "xferrecords", "xfer"},
    "refx": {"refx", "re fx", "refx"},
    "fabfilter": {"fab filter", "fabfilter"},
    "soundtoys": {"sound toys", "soundtoys"},
    "waves": {"waves audio", "wavesaudio", "waves shell", "waveshell", "waves"},
    "valhalla": {"valhalla dsp", "valhalladsp", "valhalla dsp llc"},
    "u-he": {"uhe", "u he", "u-he"},
    "arturia": {"arturia sa", "arturia"},
    "spectrasonics": {"spectrasonics inc", "spectrasonics"},
    "image-line": {"image line", "imageline", "il", "image-line"},
    "steinberg": {"steinberg media technologies", "steinberg"},
    "antares": {"antares tech", "antares"},
    "cableguys": {"cable guys", "cableguys"},
    "output": {"output"},
    "xln audio": {"xln audio", "xlnaudio", "xln"},
    "oeksound": {"oeksound", "oek sound"},
    "soundtheory": {"sound theory", "soundtheory"},
    "slate digital": {"slate", "slate digital", "slatedigital"},
    "plugin alliance": {"plugin alliance", "brainworx", "brainworx"},
    "brainworx": {"brainworx", "bx"},
    "bitsonic": {"bitsonic"},
    "vital": {"vital audio", "vital"},
    "softube": {"softube"},
    "acustica": {"acustica audio", "acustica"},
    "melda": {"melda production", "meldaproduction"},
    "splice": {"splice"},
    "universal audio": {"ua", "universal audio", "uad"},
    "roland": {"roland cloud", "roland"},
    "pre sonus": {"presonus", "pre sonus"},
    "sugar bytes": {"sugar bytes", "sugarbytes"},
    "kilohearts": {"kilohearts", "kilo hearts"},
    "reveal sound": {"reveal sound", "revealsound"},
    "syntheway": {"syntheway"},
    "uvi": {"uvi", "uvi workstation"},
    "spitfire": {"spitfire audio", "spitfire"},
    "heavyocity": {"heavyocity"},
    "excite audio": {"excite audio"},
    "sonarworks": {"sonarworks"},
    "d16": {"d16 group", "d16"},
    "toneboosters": {"toneboosters"},
    "voxengo": {"voxengo"},
    "stillwell": {"stillwell"},
    "klanghelm": {"klanghelm"},
    "tone empire": {"tone empire"},
    "psp": {"psp audioware", "psp"},
    "overloud": {"overloud"},
    "boz": {"boz digital", "boz"},
    "eventide": {"eventide"},
    "lexicon": {"lexicon"},
    "softube": {"softube"},
}

# Product key (canonical) -> set of name variants (ref names from FL, scan stems, etc.)
# Order: most-used first, then by vendor
PRODUCT_ALIASES = {
    # --- Synths & instruments (most used) ---
    "serum": {"serum", "serum 2", "serum2", "serum64", "serum 64", "serum_x64", "serum x64", "xfer serum", "xfer records serum"},
    "kontakt": {
        "kontakt", "kontakt 5", "kontakt 6", "kontakt 7", "kontakt 8",
        "kontakt5", "kontakt6", "kontakt7", "kontakt8",
        "native instruments kontakt", "native instruments kontakt 5", "native instruments kontakt 6", "native instruments kontakt 7", "native instruments kontakt 8",
        "native instrument kontakt", "native instrument kontakt 5", "native instrument kontakt 6", "native instrument kontakt 7", "native instrument kontakt 8",
        "ni kontakt", "ni kontakt 5", "ni kontakt 6", "ni kontakt 7", "ni kontakt 8",
    },
    "nexus": {"nexus", "nexus 2", "nexus 3", "nexus 4", "nexus 5", "nexus2", "nexus3", "nexus4", "nexus5", "refx nexus", "re fx nexus"},
    "omnisphere": {"omnisphere", "omnisphere 2", "spectrasonics omnisphere"},
    "keyscape": {"keyscape", "spectrasonics keyscape"},
    "trilian": {"trilian", "spectrasonics trilian"},
    "stylus rmx": {"stylus rmx", "stylus rmx 2", "spectrasonics stylus"},
    "massive": {"massive", "massive x", "native instruments massive", "ni massive"},
    "vital": {"vital", "vital audio"},
    "pigments": {"pigments", "pigments 2", "pigments 3", "arturia pigments"},
    "analog lab": {"analog lab", "analog lab v", "arturia analog lab"},
    "diva": {"diva", "u-he diva"},
    "zebra": {"zebra", "zebra2", "zebra 2", "u-he zebra"},
    "hive": {"hive", "hive 2", "hive2", "u-he hive"},
    "repro": {"repro", "repro-1", "repro-5", "u-he repro"},
    "arcade": {"arcade", "output arcade"},
    "xpand": {"xpand", "xpand 2", "xpand2", "air xpand"},
    "zenology": {"zenology", "roland zenology"},
    "dune": {"dune", "dune 2", "dune 3", "synapse dune"},
    "spire": {"spire", "reveal sound spire"},
    "sylenth1": {"sylenth1", "sylenth 1", "lennardigital sylenth1"},
    "phase plant": {"phase plant", "kilohearts phase plant"},
    "keyzone classic": {"keyzone classic", "keyzone classic piano", "bitsonic keyzone classic", "lp keyzone classic"},
    "808": {"808", "808 bass", "808 kick", "808 snare", "808 hihat", "808 hi-hat"},
    "close grand": {"close grand", "close grand piano"},
    # --- Valhalla DSP ---
    "valhalla delay": {"valhalla delay", "valhalladelay", "valhalla dsp llc valhalla delay", "valhalla dsp llc valhalladelay"},
    "valhalla vintage verb": {"valhalla vintage verb", "valhallavintageverb", "valhalla vintageverb", "valhalla dsp llc valhalla vintage verb", "valhalla dsp llc valhallavintageverb"},
    "valhalla shimmer": {"valhalla shimmer", "valhallashimmer", "valhalla dsp llc valhalla shimmer", "valhalla dsp llc valhallashimmer"},
    "valhalla room": {"valhalla room", "valhallaroom", "valhalla dsp llc valhalla room", "valhalla dsp llc valhallaroom"},
    "valhalla supermassive": {"valhalla supermassive", "valhallasupermassive", "valhalla dsp llc valhalla supermassive"},
    "valhalla plate": {"valhalla plate", "valhallaplate"},
    "valhalla uber mod": {"valhalla uber mod", "valhallaubermod"},
    "valhalla freq echo": {"valhalla freq echo", "valhallafreqecho"},
    "valhalla space mod": {"valhalla space mod"},
    "valhalla futureverb": {"valhalla futureverb", "valhalla future verb"},
    # --- FabFilter ---
    "pro-q": {"pro-q", "pro q", "pro-q 3", "pro-q 4", "pro q 3", "pro q 4", "fabfilter pro-q 3", "fabfilter pro-q 4"},
    "pro-c": {"pro-c", "pro c", "pro-c 2", "pro-c 3", "pro c 2", "fabfilter pro-c 2"},
    "pro-l": {"pro-l", "pro l", "pro-l 2", "pro l 2", "fabfilter pro-l 2"},
    "pro-mb": {"pro-mb", "pro mb", "fabfilter pro-mb"},
    "pro-r": {"pro-r", "pro r", "pro-r 2", "fabfilter pro-r"},
    "pro-ds": {"pro-ds", "pro ds", "fabfilter pro-ds"},
    "pro-g": {"pro-g", "pro g", "fabfilter pro-g"},
    "saturn": {"saturn", "saturn 2", "fabfilter saturn", "fabfilter saturn 2"},
    "timeless": {"timeless", "timeless 2", "fabfilter timeless"},
    "volcano": {"volcano", "volcano 2", "fabfilter volcano"},
    "one": {"fabfilter one", "fab filter one"},
    "micro": {"fabfilter micro", "fab filter micro"},
    # --- iZotope ---
    "ozone": {"ozone", "ozone 8", "ozone 9", "ozone 10", "ozone 11", "ozone 12", "izotope ozone", "ozone advanced", "ozone standard"},
    "neutron": {"neutron", "neutron 3", "neutron 4", "neutron 5", "izotope neutron"},
    "nectar": {"nectar", "nectar 3", "nectar 4", "izotope nectar"},
    "rx": {"rx", "rx 10", "rx 11", "izotope rx"},
    "insight": {"insight", "izotope insight"},
    "trash": {"trash", "trash 2", "izotope trash"},
    "vinyl": {"vinyl", "izotope vinyl", "izotope inc izotope vinyl", "i zotope vinyl"},
    # --- Soundtoys ---
    "decapitator": {"decapitator", "soundtoys decapitator"},
    "little plate": {"little plate", "soundtoys little plate"},
    "devil-loc": {"devil-loc", "devil loc", "soundtoys devil-loc"},
    "echoboy": {"echoboy", "echo boy", "soundtoys echoboy"},
    "crystallizer": {"crystallizer", "soundtoys crystallizer"},
    "tremolator": {"tremolator", "soundtoys tremolator"},
    "filterfreak": {"filterfreak", "filter freak", "soundtoys filterfreak"},
    "primaltap": {"primaltap", "primal tap", "soundtoys primaltap"},
    "panman": {"panman", "pan man", "soundtoys panman"},
    "phase mistress": {"phase mistress", "soundtoys phase mistress"},
    # --- Cableguys ---
    "halftime": {"halftime", "half time", "cableguys halftime"},
    "shaperbox": {"shaperbox", "shaperbox 2", "shaperbox 3", "shaperbox2", "shaperbox3", "cableguys shaperbox"},
    "volumeshaper": {"volumeshaper", "volume shaper", "cableguys volumeshaper"},
    "kickstart": {"kickstart", "kickstart 2", "cableguys kickstart"},
    "filter shaper": {"filter shaper", "filtershaper", "cableguys filter shaper"},
    # --- Antares ---
    "auto-tune": {"auto-tune", "auto tune", "antares auto-tune", "autotune"},
    "auto-tune efx": {"auto-tune efx", "auto-tune efx+", "antares auto-tune efx", "autotune efx"},
    "auto-tune pro": {"auto-tune pro", "antares auto-tune pro"},
    # --- Output ---
    "portal": {"portal", "output portal"},
    "thermal": {"thermal", "output thermal"},
    "movement": {"movement", "output movement"},
    # --- XLN Audio ---
    "rc-20": {"rc-20", "rc 20", "rc-20 retro color", "rc20", "xln rc-20", "xlnaudio rc-20"},
    "addictive keys": {"addictive keys", "addictivekeys", "xln addictive keys"},
    "addictive drums": {"addictive drums", "addictivedrums"},
    # --- Oeksound / SoundTheory ---
    "soothe": {"soothe", "soothe 2", "soothe2", "oeksound soothe", "oeksound soothe2"},
    "gullfoss": {"gullfoss", "gullfoss master", "soundtheory gullfoss"},
    # --- Waves (common) ---
    "waveshell": {"waveshell", "waveshell-vst3", "waveshell vst3", "wave shell"},
    "ssl e-channel": {"ssl e-channel", "ssl e channel", "waves ssl e-channel"},
    "api 2500": {"api 2500", "waves api 2500"},
    "cla-2a": {"cla-2a", "cla 2a", "waves cla-2a"},
    "c1 comp": {"c1 comp", "c1 compressor", "waves c1"},
    "rcomp": {"rcomp", "waves rcomp"},
    "rverb": {"rverb", "waves rverb"},
    "l1 limiter": {"l1 limiter", "waves l1"},
    "h-delay": {"h-delay", "h delay", "waves h-delay"},
    "fresh air": {"fresh air", "slate digital fresh air"},
    # --- Plugin Alliance / Brainworx ---
    "bx_console ssl 4000": {"bx_console ssl 4000 g", "bx_console ssl 4000 e", "brainworx ssl 4000"},
    "bx_console neve": {"bx_console n", "brainworx console n"},
    "ssl 4000": {"ssl 4000", "ssl4000"},
    # --- Arturia ---
    "pigments": {"pigments", "pigments 2", "pigments 3", "arturia pigments"},
    "analog lab": {"analog lab", "analog lab v", "arturia analog lab"},
    "v collection": {"v collection", "arturia v collection"},
    "jup-8": {"jup-8", "jup 8", "arturia jup-8"},
    "minimoog": {"minimoog v", "arturia minimoog"},
    # --- u-he ---
    "diva": {"diva", "u-he diva"},
    "zebra": {"zebra", "zebra2", "zebra 2", "u-he zebra"},
    "hive": {"hive", "hive 2", "hive2", "u-he hive"},
    "repro": {"repro", "repro-1", "repro-5", "u-he repro"},
    "bazille": {"bazille", "u-he bazille"},
    "ace": {"ace", "u-he ace"},
    # --- Xfer ---
    "ott": {"ott", "xfer ott", "xfer records ott"},
    "dimension exp": {"dimension expander", "xfer dimension expander", "xfer dimension"},
    "lfo tool": {"lfo tool", "xfer lfo tool"},
    # --- Slate Digital ---
    "virtual mix rack": {"virtual mix rack", "vmr", "slate digital vmr"},
    "fresh air": {"fresh air", "slate fresh air"},
    # --- Other popular ---
    "sausage fattener": {"sausage fattener", "dada life sausage fattener"},
    "lfo tool": {"lfo tool", "xfer lfo tool"},
    "gross beat": {"gross beat", "grossbeat", "image-line gross beat"},
    "newtone": {"newtone", "new tone", "image-line newtone"},
    "pitcher": {"pitcher", "image-line pitcher"},
    "vocodex": {"vocodex", "image-line vocodex"},
    "maximus": {"maximus", "image-line maximus"},
    "hardcore": {"hardcore", "image-line hardcore"},
    "directwave": {"directwave", "direct wave", "image-line directwave"},
    "harmor": {"harmor", "image-line harmor"},
    "sytrus": {"sytrus", "image-line sytrus"},
    "sakura": {"sakura", "image-line sakura"},
    "harmless": {"harmless", "image-line harmless"},
    "slicex": {"slicex", "slice x", "image-line slicex"},
    "poizone": {"poizone", "image-line poizone"},
    "toxic biohazard": {"toxic biohazard", "image-line toxic"},
    "sawer": {"sawer", "image-line sawer"},
    "morphine": {"morphine", "image-line morphine"},
}

# Token rewrites: compound/camelCase -> space-separated (before alias lookup)
TOKEN_REWRITES = [
    ("nativeinstruments", "native instruments"),
    ("kontakt5", "kontakt 5"),
    ("kontakt6", "kontakt 6"),
    ("kontakt7", "kontakt 7"),
    ("kontakt8", "kontakt 8"),
    ("serum_x64", "serum"),
    ("serum x64", "serum"),
    ("xferrecords", "xfer"),
    ("xfer records", "xfer"),
    ("fabfilter", "fab filter"),
    ("soundtoys", "sound toys"),
    ("valhalladsp", "valhalla dsp"),
    ("imageline", "image line"),
    ("valhalladelay", "valhalla delay"),
    ("valhallavintageverb", "valhalla vintage verb"),
    ("valhallashimmer", "valhalla shimmer"),
    ("valhallaroom", "valhalla room"),
    ("valhallasupermassive", "valhalla supermassive"),
    ("valhallaplate", "valhalla plate"),
    ("valhallaubermod", "valhalla uber mod"),
    ("valhallafreqecho", "valhalla freq echo"),
    ("soothe2", "soothe 2"),
    ("shaperbox3", "shaperbox 3"),
    ("omnisphere2", "omnisphere 2"),
    ("nexus5", "nexus 5"),
    ("nexus4", "nexus 4"),
    ("nexus3", "nexus 3"),
    ("nexus2", "nexus 2"),
    ("keyzoneclassic", "keyzone classic"),
    ("halftime", "half time"),
    ("devilloc", "devil loc"),
    ("echoboy", "echo boy"),
    ("filterfreak", "filter freak"),
    ("volumeshaper", "volume shaper"),
    ("autotune", "auto tune"),
    ("addictivekeys", "addictive keys"),
    ("addictivedrums", "addictive drums"),
    ("waveshell", "waves shell"),
    ("grossbeat", "gross beat"),
    ("newtone", "new tone"),
    ("slicex", "slice x"),
    ("directwave", "direct wave"),
    ("toxicbiohazard", "toxic biohazard"),
]
